/**
 * 中国银行注册表（322 家）· spec-20260922-v1
 *
 * ⚠️ 本文件由 `assets/merge_assets.py` **自动生成，不要手改**。
 * SYNC: life-assisitant-ui-desktop/src/constants/banks.ts（两端逐字一致，SHA256 校验）
 *
 * 数据来源：
 *  - 银行清单：master-xia/china_banks_list 的 banks.json（322 家）
 *  - **图标**：老大从 **iconfont** 导出的 200×200 PNG（优先）+ 脚本下载的 48×48 PNG（补覆盖）
 *  - ⚠️ 源注册表**缺 8 家**（杭州银行 / 微众 / 苏宁 / 烟台 / 农业发展 / 人民银行 / 兰考农商 / 农村信用社），已手工补入
 *
 * 字段：
 * - `code` ：内部稳定 id（存 `accounts.institution`）= 英文简称小写 或 联行号
 * - `py`   ：`short`（**简称**）的拼音首字母串。「杭州银行」→ `HZ`
 *            ⚠️ 必须用简称算 —— 用全称的话「中国工商银行」会排到 Z，用户找的是「工商银行」→ G
 * - `hot`  ：选择器「常用」段置顶（31 家）
 * - `logo` ：**真实存在的文件名**（不含扩展名，指向 `public/bank-logos/<logo>.png`）
 *            ⚠️ 绝不预填。它可能是 `yinhang-hangzhou`（iconfont 拼音名）也可能是 `icbc`（脚本名），
 *            **两种命名并存是刻意的** —— 改名会触发批量文件操作，不值得
 */
export interface BankDef {
  /** 内部稳定 id，存进 accounts.institution */
  code: string
  /** 全称，如「中国建设银行」 */
  name: string
  /** 简称，如「建设银行」；字母分组与文字徽标都以它为准 */
  short: string
  /** 简称的拼音首字母串（大写），分组取 [0] */
  py: string
  /** 置顶（选择器「常用」段） */
  hot?: boolean
  /** public/bank-logos/<logo>.png 的文件名（不含扩展名）；缺省 = 无图标，走文字徽标 */
  logo?: string
}

export const BANKS: readonly BankDef[] = [
  { code: 'icbc', name: '中国工商银行', short: '工商银行', py: 'GSYH', hot: true, logo: 'yinhang-gongshang' },
  { code: 'abc', name: '中国农业银行', short: '农业银行', py: 'NYYH', hot: true, logo: 'yinhang-nonghang' },
  { code: 'boc', name: '中国银行', short: '中国银行', py: 'ZGYH', hot: true, logo: 'yinhang-zhongguoyinhang' },
  { code: 'ccb', name: '中国建设银行', short: '建设银行', py: 'JSYH', hot: true, logo: 'yinhang-jianshe' },
  { code: 'psbc', name: '中国邮政储蓄银行', short: '邮政储蓄银行', py: 'YZCXYH', hot: true, logo: 'yinhang-youzhengchuxu' },
  { code: 'comm', name: '交通银行', short: '交通银行', py: 'JTYH', hot: true, logo: 'yinhang-jiaotong' },
  { code: 'cmb', name: '招商银行', short: '招商银行', py: 'ZSYH', hot: true, logo: 'yinhang-zhaoshang' },
  { code: 'spdb', name: '上海浦东发展银行', short: '浦发银行', py: 'PFYH', hot: true, logo: 'yinhang-pufa' },
  { code: 'cib', name: '兴业银行', short: '兴业银行', py: 'XYYH', hot: true, logo: 'yinhang-fujianxingye-' },
  { code: 'hxbank', name: '华夏银行', short: '华夏银行', py: 'HXYH', hot: true, logo: 'yinhang-huaxia' },
  { code: 'gdb', name: '广发银行', short: '广东发展银行', py: 'GDFZYH', hot: true, logo: 'gdb' },
  { code: 'cmbc', name: '中国民生银行', short: '民生银行', py: 'MSYH', hot: true, logo: 'yinhang-minsheng' },
  { code: 'citic', name: '中信银行', short: '中信银行', py: 'ZXYH', hot: true, logo: 'yinhang-zhongxin' },
  { code: 'ceb', name: '中国光大银行', short: '光大银行', py: 'GDYH', hot: true, logo: 'yinhang-guangda' },
  { code: 'egbank', name: '恒丰银行', short: '恒丰银行', py: 'HFYH', hot: true, logo: 'yinhang-hengfeng' },
  { code: 'czbank', name: '浙商银行', short: '浙商银行', py: 'ZSYH', hot: true, logo: 'yinhang-zheshang' },
  { code: 'bohaib', name: '渤海银行', short: '渤海银行', py: 'BHYH', hot: true, logo: 'bohaib' },
  { code: 'spabank', name: '平安银行', short: '平安银行', py: 'PAYH', hot: true, logo: 'yinhang-pingan' },
  { code: 'hkbea', name: '东亚银行', short: '东亚银行', py: 'DYYH', logo: 'yinhang-dongya' },
  { code: 'hanabank', name: '韩亚银行', short: '韩亚银行', py: 'HYYH', logo: 'hanabank' },
  { code: 'shrcb', name: '上海农村商业银行', short: '上海农商银行', py: 'SHNSYH', logo: 'shrcb' },
  { code: 'bjbank', name: '北京银行', short: '北京银行', py: 'BJYH', hot: true, logo: 'yinhang-beijingyinhang-' },
  { code: 'shbank', name: '上海银行', short: '上海银行', py: 'SHYH', hot: true, logo: 'yinhang-shanghai' },
  { code: 'jsbank', name: '江苏银行', short: '江苏银行', py: 'JSYH', hot: true, logo: 'jsbank' },
  { code: 'njcb', name: '南京银行', short: '南京银行', py: 'NJYH', hot: true, logo: 'yinhang-nanjing' },
  { code: 'nbbank', name: '宁波银行', short: '宁波银行', py: 'NBYH', hot: true, logo: 'yinhang-ningbo' },
  { code: 'hsbank', name: '徽商银行', short: '徽商银行', py: 'HSYH', hot: true, logo: 'hsbank' },
  { code: 'cscb', name: '长沙银行', short: '长沙银行', py: 'CSYH', hot: true, logo: 'cscb' },
  { code: 'cqbank', name: '重庆银行', short: '重庆银行', py: 'CQYH', hot: true, logo: 'cqbank' },
  { code: 'dlb', name: '大连银行', short: '大连银行', py: 'DLYH', hot: true, logo: 'yinhang-dalianyinhang-' },
  { code: 'fjhxbc', name: '福建海峡银行', short: '福建海峡银行', py: 'FJHXYH', logo: 'fjhxbc' },
  { code: 'hkb', name: '汉口银行', short: '汉口银行', py: 'HKYH', hot: true, logo: 'hkb' },
  { code: 'wzcb', name: '温州银行', short: '温州银行', py: 'WZYH', logo: 'wzcb' },
  { code: 'qdccb', name: '青岛银行', short: '青岛银行', py: 'QDYH', logo: 'yinhang-qingdaoyinhang-' },
  { code: 'tzcb', name: '台州银行', short: '台州银行', py: 'TZYH', logo: 'tzcb' },
  { code: 'jxbank', name: '嘉兴银行', short: '嘉兴银行', py: 'JXYH', logo: 'jxbank' },
  { code: 'csrcb', name: '常熟农村商业银行', short: '常熟农商银行', py: 'CSNSYH', logo: 'csrcb' },
  { code: 'nhb', name: '南海农商银行', short: '南海农村信用联社', py: 'NHNCXYLS' },
  { code: 'h3cb', name: '内蒙古银行', short: '内蒙古银行', py: 'NMGYH', logo: 'h3cb' },
  { code: 'sxcb', name: '绍兴银行', short: '绍兴银行', py: 'SXYH', logo: 'sxcb' },
  { code: 'wjrcb', name: '吴江农商银行', short: '吴江农村商业银行', py: 'WJNCSYYH', logo: 'wjrcb' },
  { code: 'zbcb', name: '齐商银行', short: '齐商银行', py: 'QSYH', logo: 'zbcb' },
  { code: 'gycb', name: '贵阳银行', short: '贵阳市商业银行', py: 'GYSSYYH', logo: 'gycb' },
  { code: 'hzccb', name: '湖州市商业银行', short: '湖州银行', py: 'HZYH', logo: 'hzccb' },
  { code: 'daqingb', name: '龙江银行', short: '龙江银行', py: 'LJYH', logo: 'daqingb' },
  { code: 'jcbank', name: '晋城银行', short: '晋城银行', py: 'JCYH' },
  { code: 'zjtlcb', name: '浙江泰隆商业银行', short: '泰隆银行', py: 'TLYH', logo: 'zjtlcb' },
  { code: 'gdrcc', name: '广东省农村信用社联合社', short: '广东农村信用社', py: 'GDNCXYS' },
  { code: 'drcbcl', name: '东莞农村商业银行', short: '东莞农村商业银行', py: 'DGNCSYYH', logo: 'drcbcl' },
  { code: 'mtbank', name: '浙江民泰商业银行', short: '民泰银行', py: 'MTYH', logo: 'mtbank' },
  { code: 'gcb', name: '广州银行', short: '广州市商业银行', py: 'GZSSYYH', hot: true, logo: 'guangzhoushishangyeyinhang-' },
  { code: 'lycb', name: '辽阳银行', short: '辽阳市商业银行', py: 'LYSSYYH', logo: 'lycb' },
  { code: 'jsrcu', name: '江苏省农村信用社联合社', short: '江苏农村信用社', py: 'JSNCXYS', logo: 'jsrcu' },
  { code: 'langfb', name: '廊坊银行', short: '廊坊银行', py: 'LFYH', logo: 'langfb' },
  { code: 'czcb', name: '浙江稠州商业银行', short: '稠州银行', py: 'CZYH', logo: 'czcb' },
  { code: 'jzbank', name: '晋中银行', short: '晋中市商业银行', py: 'JZSSYYH', logo: 'jzbank' },
  { code: 'bosz', name: '苏州银行', short: '苏州银行', py: 'SZYH' },
  { code: 'glbank', name: '桂林银行', short: '桂林银行', py: 'GLYH', logo: 'glbank' },
  { code: 'cdrcb', name: '成都农商银行', short: '成都农村商业银行', py: 'CDNCSYYH', logo: 'cdrcb' },
  { code: 'zrcbank', name: '张家港农村商业银行', short: '张家港农商银行', py: 'ZJGNSYH', logo: 'zrcbank' },
  { code: 'lsbank', name: '莱商银行', short: '莱商银行', py: 'LSYH', logo: 'lsbank' },
  { code: 'bjrcb', name: '北京农村商业银行', short: '北京农商银行', py: 'BJNSYH', hot: true, logo: 'bjrcb' },
  { code: 'trcb', name: '天津农商银行', short: '天津农村商业银行', py: 'TJNCSYYH' },
  { code: 'srbank', name: '上饶银行', short: '上饶银行', py: 'SRYH', logo: 'srbank' },
  { code: 'fdb', name: '富滇银行', short: '富滇银行', py: 'FDYH' },
  { code: 'crcbank', name: '重庆农村商业银行', short: '重庆农村商业银行', py: 'CQNCSYYH', logo: 'crcbank' },
  { code: 'ascb', name: '鞍山银行', short: '鞍山银行', py: 'ASYH', logo: 'ascb' },
  { code: 'nxbank', name: '宁夏银行', short: '宁夏银行', py: 'NXYH', logo: 'nxbank' },
  { code: 'bhb', name: '河北银行', short: '河北银行', py: 'HBYH', logo: 'yinhang-hebeiyinhang--' },
  { code: 'hrxjb', name: '华融湘江银行', short: '华融湘江银行', py: 'HRXJYH', logo: 'hrxjb' },
  { code: 'zgccb', name: '自贡市商业银行', short: '自贡市商业银行', py: 'ZGSSYYH' },
  { code: 'ynrcc', name: '云南省农村信用社', short: '云南省农村信用社联合社', py: 'YNSNCXYS', logo: 'ynrcc' },
  { code: 'jlbank', name: '吉林银行', short: '吉林银行', py: 'JLYH', logo: 'jlbank' },
  { code: 'klb', name: '昆仑银行', short: '昆仑银行', py: 'KLYH', logo: 'klb' },
  { code: 'orbank', name: '鄂尔多斯银行', short: '鄂尔多斯银行', py: 'EEDSYH', logo: 'orbank' },
  { code: 'xtb', name: '邢台银行', short: '邢台银行', py: 'XTYH', logo: 'xtb' },
  { code: 'jsb', name: '晋商银行', short: '晋商银行', py: 'JSYH', logo: 'jsb' },
  { code: 'tccb', name: '天津银行', short: '天津市商业银行', py: 'TJSSYYH', logo: 'yinhang-tianjinyinhang-' },
  { code: 'boyk', name: '营口银行', short: '营口银行', py: 'YKYH', logo: 'boyk' },
  { code: 'jlrcu', name: '吉林省农村信用社联合社', short: '吉林农信', py: 'JLNX' },
  { code: 'sdrcu', name: '山东省农村信用社', short: '山东农信', py: 'SDNX' },
  { code: 'xabank', name: '西安银行', short: '西安银行', py: 'XAYH', logo: 'xabank' },
  { code: 'hbrcu', name: '河北省农村信用社', short: '河北省农村信用社联合社', py: 'HBSNCXYS' },
  { code: 'nxrcu', name: '宁夏黄河农村商业银行', short: '黄河农村商业银行', py: 'HHNCSYYH' },
  { code: 'gzrcu', name: '贵州省农村信用社', short: '贵州省农村信用社联合社', py: 'GZSNCXYS', logo: 'gzrcu' },
  { code: 'fxcb', name: '阜新银行', short: '阜新银行', py: 'FXYH', logo: 'fxcb' },
  { code: 'zjnx', name: '浙江省农村信用社联合社', short: '浙江农村信用社', py: 'ZJNCXYS' },
  { code: 'lsccb', name: '乐山市商业银行', short: '乐山市商业银行', py: 'LSSSYYH', logo: 'lsccb' },
  { code: 'tcrcb', name: '江苏太仓农村商业银行', short: '太仓农商银行', py: 'TCNSYH' },
  { code: 'bzmd', name: '驻马店银行', short: '驻马店银行', py: 'ZMDYH', logo: 'bzmd' },
  { code: 'gzb', name: '赣州银行', short: '赣州银行', py: 'GZYH', logo: 'gzb' },
  { code: 'wrcb', name: '无锡农村商业银行', short: '无锡农村商业银行', py: 'WXNCSYYH' },
  { code: 'bgb', name: '广西北部湾银行', short: '广西北部湾银行', py: 'GXBBWYH' },
  { code: 'grcb', name: '广州农商银行', short: '广州农商银行', py: 'GZNSYH' },
  { code: 'jrcb', name: '江阴农商银行', short: '江苏江阴农村商业银行', py: 'JSJYNCSY', logo: 'jrcb' },
  { code: 'bop', name: '平顶山银行', short: '平顶山银行', py: 'PDSYH', logo: 'bop' },
  { code: 'cgnb', name: '南充市商业银行', short: '南充市商业银行', py: 'NCSSYYH' },
  { code: 'ccqtgb', name: '重庆三峡银行', short: '重庆三峡银行', py: 'CQSXYH', logo: 'ccqtgb' },
  { code: 'xlbank', name: '中山小榄村镇银行', short: '中山小榄村镇银行', py: 'ZSXLCZYH' },
  { code: 'hdbank', name: '邯郸银行', short: '邯郸银行', py: 'HDYH', logo: 'hdbank' },
  { code: 'korlabank', name: '库尔勒市商业银行', short: '库尔勒市商业银行', py: 'KELSSYYH' },
  { code: 'bojz', name: '锦州银行', short: '锦州银行', py: 'JZYH', logo: 'bojz' },
  { code: 'qlbank', name: '齐鲁银行', short: '齐鲁银行', py: 'QLYH', logo: 'qlbank' },
  { code: 'boqh', name: '青海银行', short: '青海银行', py: 'QHYH', logo: 'boqh' },
  { code: 'sjbank', name: '盛京银行', short: '盛京银行', py: 'SJYH', logo: 'sjbank' },
  { code: 'fscb', name: '抚顺银行', short: '抚顺市商业银行', py: 'FSSSYYH', logo: 'fscb' },
  { code: 'zzbank', name: '郑州银行', short: '郑州银行', py: 'ZZYH', logo: 'yinhang-zhengzhouyinhang-' },
  { code: 'srcb', name: '深圳农村商业银行', short: '深圳农商银行', py: 'SZNSYH', logo: 'srcb' },
  { code: 'bankwf', name: '潍坊银行', short: '潍坊银行', py: 'WFYH', logo: 'bankwf' },
  { code: 'jjbank', name: '九江银行', short: '九江银行', py: 'JJYH', logo: 'jjbank' },
  { code: 'jxrcu', name: '江西省农村信用社', short: '江西省农村信用社联合社', py: 'JXSNCXYS' },
  { code: 'hnrcu', name: '河南省农村信用社', short: '河南省农村信用社联合社', py: 'HNSNCXYS' },
  { code: 'gsrcu', name: '甘肃省农村信用社', short: '甘肃省农村信用社联合社', py: 'GSSNCXYS', logo: 'gsrcu' },
  { code: 'scrcu', name: '四川省农村信用社', short: '四川省农村信用社联合社', py: 'SCSNCXYS' },
  { code: 'gxrcu', name: '广西省农村信用社', short: '广西农村信用社联合社', py: 'GXNCXYSL' },
  { code: 'sxrccu', name: '陕西信合', short: '陕西省农村信用社联合社', py: 'SXSNCXYS', logo: 'sxrccu' },
  { code: 'whrcb', name: '武汉农村商业银行', short: '武汉农商银行', py: 'WHNSYH' },
  { code: 'ybccb', name: '宜宾市商业银行', short: '宜宾市商业银行', py: 'YBSSYYH', logo: 'ybccb' },
  { code: 'szsbk', name: '石嘴山银行', short: '石嘴山银行', py: 'SZSYH', logo: 'szsbk' },
  { code: 'hsbk', name: '衡水银行', short: '衡水市商业银行', py: 'HSSSYYH', logo: 'hsbk' },
  { code: 'xybank', name: '信阳银行', short: '信阳银行', py: 'XYYH', logo: 'xybank' },
  { code: 'zjkccb', name: '张家口市商业银行', short: '张家口市商业银行', py: 'ZJKSSYYH' },
  { code: 'jnbank', name: '济宁银行', short: '济宁银行', py: 'JNYH', logo: 'jnbank' },
  { code: 'whccb', name: '威海市商业银行', short: '威海市商业银行', py: 'WHSSYYH' },
  { code: 'hbc', name: '湖北银行', short: '湖北银行', py: 'HBYH', logo: 'hbc' },
  { code: 'bocd', name: '承德银行', short: '承德银行', py: 'CDYH', logo: 'bocd' },
  { code: 'bodd', name: '丹东银行', short: '丹东银行', py: 'DDYH', logo: 'bodd' },
  { code: 'jhbank', name: '金华银行', short: '金华商业银行', py: 'JHSYYH', logo: 'jhbank' },
  { code: 'bocy', name: '朝阳银行', short: '朝阳银行', py: 'ZYYH', logo: 'bocy' },
  { code: 'lsbc', name: '临商银行', short: '临沂商业银行', py: 'LYSYYH', logo: 'lsbc' },
  { code: 'bsb', name: '包商银行', short: '包商银行', py: 'BSYH', logo: 'bsb' },
  { code: 'lzyh', name: '兰州银行', short: '兰州银行', py: 'LZYH', logo: 'lzyh' },
  { code: 'bozk', name: '周口银行', short: '周口银行', py: 'ZKYH' },
  { code: 'dzbank', name: '德州银行', short: '德州银行', py: 'DZYH', logo: 'dzbank' },
  { code: 'arcu', name: '安徽省农村信用社', short: '安徽省农村信用社联合社', py: 'AHSNCXYS' },
  { code: 'hnrcc', name: '湖南省农村信用社', short: '湖南省农村信用社联合社', py: 'HNSNCXYS', logo: 'hnrcc' },
  { code: 'nynb', name: '广东南粤银行', short: '广东南粤银行', py: 'GDNYYH', logo: 'nynb' },
  { code: 'lybank', name: '洛阳银行', short: '洛阳银行', py: 'LYYH', logo: 'lybank' },
  { code: '04023930', name: '厦门银行', short: '厦门银行', py: 'XMYH', logo: '04023930' },
  { code: '04643970', name: '泉州银行', short: '泉州银行', py: 'QZYH', logo: '04643970' },
  { code: '64554770', name: '日照银行', short: '日照市商业银行', py: 'RZSSYYH', logo: '64554770' },
  { code: '04933160', name: '江苏长江商业银行', short: '江苏长江商业银行', py: 'JSCJSYYH', logo: '04933160' },
  { code: '05503320', name: '宁波东海银行', short: '宁波东海银行', py: 'NBDHYH' },
  { code: '05824540', name: '枣庄银行', short: '枣庄银行', py: 'ZZYH' },
  { code: '64956140', name: '柳州银行', short: '柳州银行', py: 'LZYH', logo: '64956140' },
  { code: '05785800', name: '广东华兴银行', short: '广东华兴银行', py: 'GDHXYH' },
  { code: '64375850', name: '珠海华润银行', short: '珠海华润银行', py: 'ZHHRYH', logo: '64375850' },
  { code: '14315850', name: '珠海农商银行', short: '珠海农村商业银行', py: 'ZHNCSYYH' },
  { code: '04761432', name: '沧州银行', short: '沧州银行', py: 'CZYH', logo: '04761432' },
  { code: '05521379', name: '保定银行', short: '保定银行', py: 'BDYH', logo: '05521379' },
  { code: '04871620', name: '大同银行', short: '大同市商业银行', py: 'DTSSYYH', logo: '04871620' },
  { code: '05121660', name: '长治银行', short: '长治市商业银行', py: 'ZZSSYYH' },
  { code: '04836560', name: '攀枝花市商业银行', short: '攀枝花市商业银行', py: 'PZHSSYYH', logo: '04836560' },
  { code: '04866570', name: '泸州市商业银行', short: '泸州市商业银行', py: 'LZSSYYH', logo: '04866570' },
  { code: '05516629', name: '遂宁市商业银行', short: '遂宁市商业银行', py: 'SNSSYYH' },
  { code: '05847000', name: '贵州银行', short: '贵州银行', py: 'GZYH', logo: '05847000' },
  { code: '05027361', name: '曲靖市商业银行', short: '曲靖市商业银行', py: 'QJSSYYH' },
  { code: '64422611', name: '哈尔滨银行', short: '哈尔滨银行', py: 'HEBYH', logo: '64422611' },
  { code: '04332369', name: '葫芦岛银行', short: '葫芦岛银行', py: 'HLDYH' },
  { code: '05417901', name: '长安银行', short: '长安银行', py: 'CAYH', logo: '05417901' },
  { code: '03210001', name: '汇丰银行', short: '汇丰银行', py: 'HFYH', logo: 'yinhang-huifeng' },
  { code: '03190001', name: '花旗银行', short: '花旗银行', py: 'HQYH', logo: 'yinhang-huaqi' },
  { code: '03220001', name: '渣打银行', short: '渣打银行', py: 'ZDYH', logo: 'yinhang-zhada' },
  { code: '03300000', name: '华侨银行', short: '华侨银行', py: 'HQYH', logo: '03300000' },
  { code: '63320000', name: '南洋商业银行', short: '南洋商业银行', py: 'NYSYYH', logo: '63320000' },
  { code: '25150344', name: '恒生银行', short: '恒生银行', py: 'HSYH', logo: '25150344' },
  { code: '03390000', name: '富邦华一银行', short: '富邦华一银行', py: 'FBHYYH', logo: '03390000' },
  { code: '03370000', name: '华商银行', short: '华商银行', py: 'HSYH', logo: '03370000' },
  { code: '03270000', name: '友利银行', short: '友利银行', py: 'YLYH', logo: '03270000' },
  { code: '03280000', name: '新韩银行', short: '新韩银行', py: 'XHYH', logo: '03280000' },
  { code: '03240000', name: '星展银行中国', short: '星展银行中国', py: 'XZYHZG' },
  { code: '03330001', name: '法国兴业银行', short: '法国兴业银行', py: 'FGXYYH', logo: '03330001' },
  { code: '14144520', name: '青岛农商银行', short: '青岛农村商业银行', py: 'QDNCSYYH' },
  { code: '65173900', name: '福建省农村信用社联合社', short: '福建农村信用社', py: 'FJNCXYS', logo: '65173900' },
  { code: '14542201', name: '辽宁省农村信用社联合社', short: '辽宁省农村信用社', py: 'LNSNCXYS' },
  { code: '63200000', name: '东亚银行(中国)', short: '东亚银行(中国)', py: 'DYYHZG' },
  { code: '01020446', name: '中国工商银行(澳门)', short: '中国工商银行澳门分行', py: 'ZGGSYHAM' },
  { code: '03290000', name: '韩亚银行(中国)', short: '韩亚银行(中国)', py: 'HYYHZG' },
  { code: '03320000', name: '南洋商业银行(中国)', short: '南洋商业银行(中国)', py: 'NYSYYHZG' },
  { code: '01040446', name: '中国银行澳门分行', short: '中国银行澳门分行', py: 'ZGYHAMFH' },
  { code: '03010344', name: '交通银行香港分行', short: '交通银行香港分行', py: 'JTYHXGFH' },
  { code: '03080344', name: '招商银行香港分行', short: '招商银行香港分行', py: 'ZSYHXGFH' },
  { code: '04856590', name: '绵阳市商业银行', short: '绵阳市商业银行', py: 'MYSSYYH', logo: '04856590' },
  { code: '14551600', name: '山西省农村信用社', short: '山西省农村信用社', py: 'SXSNCXYS' },
  { code: '05818202', name: '甘肃银行', short: '甘肃银行', py: 'GSYH', logo: '05818202' },
  { code: '05311930', name: '乌海银行', short: '乌海银行', py: 'WHYH' },
  { code: '05392339', name: '铁岭银行', short: '铁岭银行', py: 'TLYH' },
  { code: '05442329', name: '盘锦市商业银行', short: '盘锦市商业银行', py: 'PJSSYYH' },
  { code: '05556859', name: '凉山州商业银行', short: '凉山州商业银行', py: 'LSZSYYH' },
  { code: '65055810', name: '广州农村商业银行', short: '广州农村商业银行', py: 'GZNCSYYH', logo: '65055810' },
  { code: '14075882', name: '顺德农村商业银行', short: '广东顺德农村商业银行', py: 'GDSDNCSY' },
  { code: '05864910', name: '中原银行', short: '中原银行', py: 'ZYYH', logo: 'yinhang-zhongyuanyinhang-' },
  { code: '14215881', name: '佛山市三水区农村信用合作联社', short: '佛山市三水区农村信用合作联社', py: 'FSSSSQNC' },
  { code: '14333051', name: '太仓农村商业银行', short: '太仓农村商业银行', py: 'TCNCSYYH' },
  { code: '64603040', name: '江南农村商业银行', short: '江南农村商业银行', py: 'JNNCSYYH' },
  { code: '14448802', name: '新疆维吾尔自治区农村信用社联合社', short: '新疆维吾尔自治区农村信用社联合社', py: 'XJWWEZZQ' },
  { code: '14486400', name: '海南省农村信用社联合社', short: '海南省农村信用社联合社', py: 'HNSNCXYS', logo: '14486400' },
  { code: '14498501', name: '青海省农村信用社联合社', short: '青海省农村信用社联合社', py: 'QHSNCXYS' },
  { code: '14511900', name: '内蒙古自治区农村信用社联合社', short: '内蒙古自治区农村信用社联合社', py: 'NMGZZQNC' },
  { code: '65561100', name: '天津滨海农村商业银行', short: '天津滨海农商银行', py: 'TJBHNSYH', logo: '65561100' },
  { code: '14572600', name: '黑龙江省农村信用社联合社', short: '黑龙江省农村信用社联合社', py: 'HLJSNCXY' },
  { code: '03350000', name: '大新银行', short: '大新银行', py: 'DXYH', logo: '03350000' },
  { code: '25070344', name: '中国建设银行(亚洲)', short: '中国建设银行亚洲', py: 'ZGJSYHYZ' },
  { code: '25080344', name: '星展银行(香港)', short: '星展银行香港', py: 'XZYHXG' },
  { code: '25090344', name: '上海商业银行', short: '上海商业银行', py: 'SHSYYH' },
  { code: '25100344', name: '永隆银行', short: '永隆银行', py: 'YLYH' },
  { code: '25170344', name: '创兴银行', short: '创兴银行', py: 'CXYH' },
  { code: '47980344', name: '中国银行(香港)', short: '中国银行(香港)', py: 'ZGYHXG' },
  { code: '25230344', name: 'AEON信贷财务(亚洲)', short: 'AEON信贷财务亚洲', py: 'AEONXDCW' },
  { code: '01020344', name: '中国工商银行(亚洲)', short: '工银亚洲', py: 'GYYZ' },
  { code: '25250446', name: '大丰银行', short: '大丰银行', py: 'DFYH' },
  { code: '25270446', name: '中国建设银行(澳门)', short: '中国建设银行澳门', py: 'ZGJSYHAM' },
  { code: '25280344', name: '渣打银行(香港)', short: '渣打银行香港', py: 'ZDYHXG' },
  { code: '03340000', name: '大华银行', short: '大华银行', py: 'DHYH', logo: '03340000' },
  { code: '26110392', name: '三井住友银行', short: '三井住友银行', py: 'SJZYYH' },
  { code: '26220446', name: '澳门国际银行', short: '澳门国际银行', py: 'AMGJYH' },
  { code: '26230446', name: '澳门大西洋银行', short: '澳门大西洋银行', py: 'AMDXYYH' },
  { code: '26530496', name: '可汗银行', short: '可汗银行', py: 'KHYH' },
  { code: '26620496', name: '蒙古郭勒姆特银行', short: '蒙古郭勒姆特银行', py: 'MGGLMTYH' },
  { code: '26630410', name: 'BC卡', short: 'BC卡', py: 'BCK' },
  { code: '65385500', name: '湖南农村信用社联合社', short: '湖南农村信用社联合社', py: 'HNNCXYSL' },
  { code: '01040458', name: '中国银行(马来西亚)', short: '中国银行(马来西亚)', py: 'ZGYHMLXY' },
  { code: '01020276', name: '中国工商银行法兰克福分行', short: '中国工商银行法兰克福分行', py: 'ZGGSYHFL' },
  { code: '03310000', name: '华侨永亨银行(中国)', short: '华侨永亨银行(中国)', py: 'HQYHYHZG' },
  { code: '01020056', name: '中国工商银行布鲁塞尔分行', short: '中国工商银行布鲁塞尔分行', py: 'ZGGSYHBL' },
  { code: '01020076', name: '中国工商银行(巴西)', short: '中国工商银行(巴西)', py: 'ZGGSYHBX' },
  { code: '01020116', name: '中国工商银行金边分行', short: '中国工商银行金边分行', py: 'ZGGSYHJB' },
  { code: '01020124', name: '中国工商银行(加拿大)', short: '中国工商银行(加拿大)', py: 'ZGGSYHJN' },
  { code: '01020250', name: '中国工商银行巴黎分行', short: '中国工商银行巴黎分行', py: 'ZGGSYHBL' },
  { code: '01020360', name: '中国工商银行(印度尼西亚)', short: '中国工商银行(印度尼西亚)', py: 'ZGGSYHYD' },
  { code: '05767700', name: '西藏银行', short: '西藏银行', py: 'XZYH' },
  { code: '05778981', name: '新疆汇和银行', short: '新疆汇和银行', py: 'XJHHYH' },
  { code: '05832250', name: '本溪市商业银行', short: '本溪市商业银行', py: 'BXSSYYH' },
  { code: '05748844', name: '哈密市商业银行', short: '哈密市商业银行', py: 'HMSSYYH' },
  { code: '05803320', name: '宁波通商银行', short: '宁波通商银行', py: 'NBTSYH' },
  { code: '25020446', name: '东亚银行澳门分行', short: '东亚银行澳门分行', py: 'DYYHAMFH' },
  { code: '26780643', name: '俄罗斯远东商业银行', short: '俄罗斯远东商业银行', py: 'ELSYDSYY' },
  { code: '27200704', name: '越南西贡商业银行', short: '越南西贡商业银行', py: 'YNXGSYYH' },
  { code: '15265130', name: '南阳村镇银行', short: '南阳村镇银行', py: 'NYCZYH' },
  { code: '01040036', name: '中国银行(澳大利亚)', short: '中国银行(澳大利亚)', py: 'ZGYHADLY' },
  { code: '01040116', name: '中国银行金边分行', short: '中国银行金边分行', py: 'ZGYHJBFH' },
  { code: '99900410', name: '中国银行首尔分行', short: '中国银行首尔分行', py: 'ZGYHSEFH' },
  { code: '01040704', name: '中国银行胡志明市分行', short: '中国银行胡志明市分行', py: 'ZGYHHZMS' },
  { code: '01040764', name: '中国银行曼谷分行', short: '中国银行曼谷分行', py: 'ZGYHMGFH' },
  { code: '01020380', name: '中国工商银行米兰分行', short: '中国工商银行米兰分行', py: 'ZGGSYHML' },
  { code: '01020392', name: '中国工商银行东京分行', short: '中国工商银行东京分行', py: 'ZGGSYHDJ' },
  { code: '01020418', name: '中国工商银行万象分行', short: '中国工商银行万象分行', py: 'ZGGSYHWX' },
  { code: '01020442', name: '中国工商银行卢森堡分行', short: '中国工商银行卢森堡分行', py: 'ZGGSYHLS' },
  { code: '01020458', name: '中国工商银行马来西亚', short: '中国工商银行马来西亚', py: 'ZGGSYHML' },
  { code: '01020554', name: '中国工商银行新西兰', short: '中国工商银行新西兰', py: 'ZGGSYHXX' },
  { code: '01020586', name: '中国工商银行卡拉奇分行', short: '中国工商银行卡拉奇分行', py: 'ZGGSYHKL' },
  { code: '01020702', name: '中国工商银行新加坡分行', short: '中国工商银行新加坡分行', py: 'ZGGSYHXJ' },
  { code: '01020724', name: '中国工商银行马德里分行', short: '中国工商银行马德里分行', py: 'ZGGSYHMD' },
  { code: '01020826', name: '中国工商银行伦敦分行', short: '中国工商银行伦敦分行', py: 'ZGGSYHLD' },
  { code: '03010446', name: '交通银行澳门分行', short: '交通银行澳门分行', py: 'JTYHAMFH' },
  { code: '05576751', name: '达州市商业银行', short: '达州市商业银行', py: 'DZSSYYH' },
  { code: '05666770', name: '雅安市商业银行', short: '雅安市商业银行', py: 'YASSYYH' },
  { code: '05722289', name: '营口沿海银行', short: '营口沿海银行', py: 'YKYHYH', logo: '05722289' },
  { code: '14616410', name: '海口联合农村商业银行', short: '海口联合农商银行', py: 'HKLHNSYH' },
  { code: '15083333', name: '乐清联合村镇银行', short: '乐清联合村镇银行', py: 'YQLHCZYH' },
  { code: '15151000', name: '北京大兴九银村镇银行', short: '北京大兴九银村镇银行', py: 'BJDXJYCZ' },
  { code: '15173120', name: '江苏邗江民泰村镇银行', short: '江苏邗江民泰村镇银行', py: 'JSHJMTCZ' },
  { code: '15181123', name: '天津静海新华村镇银行', short: '天津静海新华村镇银行', py: 'TJJHXHCZ' },
  { code: '15193320', name: '宁波镇海中银富登村镇银行', short: '宁波镇海中银富登村镇银行', py: 'NBZHZYFD' },
  { code: '15201000', name: '北京顺义银座村镇银行', short: '北京顺义银座村镇银行', py: 'BJSYYZCZ' },
  { code: '15271329', name: '宁晋民生村镇银行', short: '宁晋民生村镇银行', py: 'NJMSCZYH' },
  { code: '15283310', name: '浙江萧山湖商村镇银行', short: '浙江萧山湖商村镇银行', py: 'ZJXSHSCZ' },
  { code: '15301750', name: '晋中市榆次融信村镇银行', short: '晋中市榆次融信村镇银行', py: 'JZSYCRXC' },
  { code: '15315960', name: '梅县客家村镇银行', short: '梅县客家村镇银行', py: 'MXKJCZYH' },
  { code: '15335840', name: '宝生村镇银行', short: '宝生村镇银行', py: 'BSCZYH' },
  { code: '15343116', name: '江苏大丰江南村镇银行', short: '江苏大丰江南村镇银行', py: 'JSDFJNCZ' },
  { code: '15354353', name: '吉安稠州村镇银行', short: '吉安稠州村镇银行', py: 'JACZCZYH' },
  { code: '15363321', name: '象山国民村镇银行', short: '象山国民村镇银行', py: 'XSGMCZYH' },
  { code: '15386423', name: '文昌国民村镇银行', short: '文昌国民村镇银行', py: 'WCGMCZYH' },
  { code: '15401000', name: '北京门头沟珠江村镇银行', short: '北京门头沟珠江村镇银行', py: 'BJMTGZJC' },
  { code: '15405881', name: '三水珠江村镇银行', short: '三水珠江村镇银行', py: 'SSZJCZYH' },
  { code: '15433613', name: '安徽肥西石银村镇银行', short: '安徽肥西石银村镇银行', py: 'AHFXSYCZ' },
  { code: '15446610', name: '广元贵商村镇银行', short: '广元贵商村镇银行', py: 'GYGSCZYH' },
  { code: '15455880', name: '佛山高明顺银村镇银行', short: '佛山高明顺银村镇银行', py: 'FSGMSYCZ' },
  { code: '15464520', name: '青岛胶南海汇村镇银行', short: '青岛胶南海汇村镇银行', py: 'QDJNHHCZ' },
  { code: '15475950', name: '惠州仲恺东盈村镇银行', short: '惠州仲恺东盈村镇银行', py: 'HZZKDYCZ' },
  { code: '15483023', name: '宜兴阳羡村镇银行', short: '宜兴阳羡村镇银行', py: 'YXYXCZYH' },
  { code: '15514550', name: '东营莱商村镇银行', short: '东营莱商村镇银行', py: 'DYLSCZYH' },
  { code: '15515134', name: '河南方城凤裕村镇银行', short: '河南方城凤裕村镇银行', py: 'HNFCFYCZ' },
  { code: '15521463', name: '永清吉银村镇银行', short: '永清吉银村镇银行', py: 'YQJYCZYH' },
  { code: '15523120', name: '江都吉银村镇银行', short: '江都吉银村镇银行', py: 'JDJYCZYH' },
  { code: '15563056', name: '张家港渝农商村镇银行', short: '张家港渝农商村镇银行', py: 'ZJGYNSCZ' },
  { code: '15572210', name: '沈阳于洪永安村镇银行', short: '沈阳于洪永安村镇银行', py: 'SYYHYACZ' },
  { code: '15581000', name: '北京房山沪农商村镇银行', short: '北京房山沪农商村镇银行', py: 'BJFSHNSC' },
  { code: '15604951', name: '宝丰豫丰村镇银行', short: '宝丰豫丰村镇银行', py: 'BFYFCZYH' },
  { code: '15624916', name: '新密郑银村镇银行', short: '新密郑银村镇银行', py: 'XMZYCZYH' },
  { code: '15633632', name: '安徽五河永泰村镇银行', short: '安徽五河永泰村镇银行', py: 'AHWHYTCZ' },
  { code: '15641100', name: '天津华明村镇银行', short: '天津华明村镇银行', py: 'TJHMCZYH' },
  { code: '15655031', name: '长葛轩辕村镇银行', short: '长葛轩辕村镇银行', py: 'ZGXYCZYH' },
  { code: '15695812', name: '从化柳银村镇银行', short: '从化柳银村镇银行', py: 'CHLYCZYH' },
  { code: '15713386', name: '浙江兰溪越商村镇银行', short: '浙江兰溪越商村镇银行', py: 'ZJLXYSCZ' },
  { code: '15752281', name: '辽宁大石桥隆丰村镇银行', short: '辽宁大石桥隆丰村镇银行', py: 'LNDSQLFC' },
  { code: '15773683', name: '枞阳泰业村镇银行', short: '枞阳泰业村镇银行', py: 'ZYTYCZYH' },
  { code: '15805364', name: '通城惠民村镇银行', short: '通城惠民村镇银行', py: 'TCHMCZYH' },
  { code: '15845013', name: '武陟射阳村镇银行', short: '武陟射阳村镇银行', py: 'WZSYCZYH' },
  { code: '15884583', name: '山东临朐聚丰村镇银行', short: '山东临朐聚丰村镇银行', py: 'SDLQJFCZ' },
  { code: '15915936', name: '德庆华润村镇银行', short: '德庆华润村镇银行', py: 'DQHRCZYH' },
  { code: '15947916', name: '西安高陵阳光村镇银行', short: '西安高陵阳光村镇银行', py: 'XAGLYGCZ' },
  { code: '16013144', name: '江苏丹阳保得村镇银行', short: '江苏丹阳保得村镇银行', py: 'JSDYBDCZ' },
  { code: '16023010', name: '江苏溧水民丰村镇银行', short: '江苏溧水民丰村镇银行', py: 'JSLSMFCZ' },
  { code: '03190003', name: '花旗中国', short: '花旗中国', py: 'HQZG' },
  { code: '03360000', name: '企业银行(中国)', short: '企业银行(中国)', py: 'QYYHZG' },
  { code: '26320446', name: '澳门商业银行', short: '澳门商业银行', py: 'AMSYYH' },
  { code: '27240608', name: '菲律宾金融银行', short: '菲律宾金融银行', py: 'FLBJRYH' },
  { code: '48080001', name: '中银通支付', short: '中银通支付', py: 'ZYTZF' },
  { code: '15494210', name: '南昌大丰村镇银行', short: '南昌大丰村镇银行', py: 'NCDFCZYH' },
  { code: '25160344', name: '中信嘉华银行', short: '中信嘉华银行', py: 'ZXJHYH' },
  { code: '14427900', name: '陕西省农村信用社', short: '农村信用社', py: 'NCXYS' },
  { code: '14505800', name: '广东省农村信用社', short: '广东农信社', py: 'GDNXS' },
  { code: 'hzcb', name: '杭州银行', short: '杭州银行', py: 'HZYH', hot: true, logo: 'yinhang-hangzhou' },
  { code: 'webank', name: '微众银行', short: '微众银行', py: 'WZYH', logo: 'yinhang-weijingyinhang-' },
  { code: 'snbank', name: '苏宁银行', short: '苏宁银行', py: 'SNYH', logo: 'yinhang-suning' },
  { code: 'ytbank', name: '烟台银行', short: '烟台银行', py: 'YTYH', logo: 'yinhang-yantaiyinhang-' },
  { code: 'adbc', name: '中国农业发展银行', short: '农业发展银行', py: 'NYFZYH', logo: 'yinhang-zhongguonongyefazhanyinhang-' },
  { code: 'pboc', name: '中国人民银行', short: '中国人民银行', py: 'ZGRMYH', logo: 'yinhang-zhongguorenminyinhang-' },
  { code: 'lkrcb', name: '兰考农商银行', short: '兰考农商银行', py: 'LKNSYH', logo: 'yinhang-lankaonongshangyinhang-' },
  { code: 'rcc', name: '农村信用社', short: '农村信用社', py: 'NCXYS', logo: 'nongcunxinyongsheyinhang-' },
] as const

export const BANK_MAP: Record<string, BankDef> = Object.fromEntries(
  BANKS.map((b) => [b.code, b])
)

export const HOT_BANKS: readonly BankDef[] = BANKS.filter((b) => b.hot)

/** A–Z 分组（字母索引用；空字母不出现） */
export const BANKS_BY_LETTER: Record<string, readonly BankDef[]> =
  BANKS.reduce<Record<string, BankDef[]>>((acc, b) => {
    const L = b.py[0] || '#'
    ;(acc[L] ||= []).push(b)
    return acc
  }, {})

/** 字母索引条：有数据的字母（升序）。⚠️ UI 上仍渲染完整 A–Z，无数据的置灰 */
export const BANK_LETTERS: readonly string[] = Object.keys(BANKS_BY_LETTER).sort()

export function findBank(code: string): BankDef | undefined {
  return code ? BANK_MAP[code] : undefined
}

/** 文字徽标兜底 */
export function bankFallback(code: string): { text: string; color: string } {
  const b = findBank(code)
  return { text: b ? (b.short || b.name).slice(0, 1) : '银', color: '#8A8A8A' }
}
